### PR TITLE
Stigma, effects, and format fixes

### PR DESCRIPTION
**Pull request by kmalone86**
Added stigma to builder for 3* heroes.
Added effect section, which looks to work fine.
Made some minor format adjustment based on new formats.

### CODE REVIEW

**Comment by RaphaelDDL** [comment]
dan,g you are doing better than me with React :D I tried to fix that issue on the select for few days, anything I did would make the functionality hahah

**Comment by RaphaelDDL** [comment]
I merged but I was thinking now.

Maybe it's better to treat effects like buff/debuff? They are buffs and debuffs, in a fashion. Having them separated would be confusing for people when filtering buffs/debuffs since I'd need to present a secondary buff/debuff based on "effects" ?

Should we merge the effects as buff/debuffs instead?

**Comment by kmalone86** [comment]
Lol, I originally had them in the buff/debuffs then moved them to effects. I forget why I moved them, probably just due to it looking weird with "stic_" next to "efct_". Or it couldn't have been due to hard to decide on some of them if they are buff or debuff, like "steal buff".

**Comment by RaphaelDDL** [comment]
I think all others are easily to categorize. Only two hard are:
- Steal Buff like you said: It's a buff dispel on the enemy (so debuff), but also is a buff for the user (with the buff user stole).. hmm.. 
- Transfer debuff: It's a buff for the user as acts as a debuff dispell, but also is a debuff for the enemy since user is transferring to them....

Well, maybe we can rule out as their main functionality, which is steal buff = grant buff to self; transfer = grant debuff to enemy ?

If it's resisted, the secondary effect (enemy dispel, and self dispel) does not happen.

For example, my ML Zerato, when countering (which act as transfer), sometimes is resisted, thus he still keeps the debuff on himself.

**Comment by kmalone86** [comment]
We could just have them in both.
stic_steal_self (buff)
stic_steal_target (debuff)

stic_trans_self   stic_trans_target

I was wondering the same about cleanse/dispel as unless I am missing something, no matter if it is self or enemy, they always seem to use the word dispel instead of cleanse.

**Comment by RaphaelDDL** [comment]
People use Cleanse when it's cleaning debuffs from your team, and dispel when it's stripping buffs from enemies, right? But yeah, I think game says dispel on all instances.

 I think it'll be easier for people to filter to on the buff/debuff rather than as separated.

But anyway, you'd prefer separated or together for the json? I can simply merge them on the API so it becomes all buff/debuff on my side, now that I thought of it.

**Comment by kmalone86** [comment]
No heroes have these new ones yet, so no harm moving it back to buff/debuff now.

Basically would just be re-applying c29a535, if I am understanding correctly.

**Pull request merged**
